#!/usr/bin/env python3
"""Generate packed-field offsets from the elaborated design, never from handwritten bit counts.
Verilator 5.040 XML is required; unsupported types fail when requested by the monitor.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def generate(source, target):
    xml = Path(source).read_text()
    # Verilator emits ANSI escape characters in diagnostic string attributes as XML 1.0
    # invalid numeric references. They do not affect types or hierarchy.
    xml = re.sub(r'&#(?:x[0-9a-fA-F]+|[0-9]+);', '', xml)
    root = ET.fromstring(xml)
    types = {t.attrib['id']: t for t in root.find('netlist/typetable')}
    modules = {m.attrib['name']: m for m in root.findall('netlist/module')}

    def number(s):
        if "'" not in s:
            return int(s)
        _, value = s.split("'", 1)
        value = value.lstrip('s')
        return int(value[1:], {'h': 16, 'd': 10, 'b': 2, 'o': 8}[value[0]])

    def bounds(t):
        r = t.find('range')
        return tuple(number(v.attrib['name']) for v in r.findall('const'))

    def unwrap(t):
        while t.tag in ('refdtype', 'enumdtype', 'constdtype'):
            t = types[t.attrib.get('sub_dtype_id') or t.attrib['dtype_id']]
        return t

    def width(t):
        t = unwrap(t)
        if t.tag == 'basicdtype':
            if 'left' in t.attrib:
                return abs(int(t.attrib['left']) - int(t.attrib['right'])) + 1
            if t.attrib['name'] in ('logic', 'bit'):
                return 1
            if t.attrib['name'] in ('int', 'integer'):
                return 32
            if t.attrib['name'] in ('longint', 'time'):
                return 64
        if t.tag in ('structdtype', 'uniondtype'):
            sizes = [width(types[m.attrib['sub_dtype_id']]) for m in t.findall('memberdtype')]
            return sum(sizes) if t.tag == 'structdtype' else max(sizes)
        if t.tag == 'packarraydtype':
            a, b = bounds(t)
            return (abs(a-b)+1)*width(types[t.attrib['sub_dtype_id']])
        raise ValueError(t.tag + ' ' + str(t.attrib))

    def fields(t, prefix='', offset=0):
        t = unwrap(t)
        result = [(prefix, offset, width(t))]
        if t.tag in ('structdtype', 'uniondtype'):
            pos = offset
            for m in reversed(t.findall('memberdtype')):
                sub = types[m.attrib['sub_dtype_id']]
                result += fields(sub, (prefix+'.' if prefix else '')+m.attrib['name'], pos)
                if t.tag == 'structdtype':
                    pos += width(sub)
        return result

    out = ['// Generated by layout.py from Verilator XML. Do not edit.', '#pragma once',
           '#include <map>', '#include <string>', 'namespace len5::diff {',
           'struct BitField { unsigned offset, width; };',
           'struct Layout { unsigned width, stride; int low, high; bool unpacked; std::map<std::string,BitField> fields; };',
           'inline const std::map<std::string,Layout> layouts = {']
    selected = {'tb_bare','issue_stage','issue_queue','commit_stage','rob','int_rf','csrs',
                'arith_rs','arith_rs_serial','arith_rs_fpu','branch_rs','load_buffer','store_buffer','branch_unit'}
    max_width = 0
    for cell in root.findall('cells//cell'):
        mod = modules[cell.attrib['submodname']]
        if mod.attrib.get('origName',mod.attrib['name']) not in selected:
            continue
        for var in mod.findall('var'):
            if var.attrib.get('param') or 'dtype_id' not in var.attrib:
                continue
            t = unwrap(types[var.attrib['dtype_id']])
            low, high, unpacked = 0, 0, t.tag == 'unpackarraydtype'
            array = t.tag in ('unpackarraydtype','packarraydtype')
            sub = t
            if array:
                a,b = bounds(t)
                low,high = min(a,b),max(a,b)
                # All monitored arrays use descending packed or ascending unpacked indices.
                if (not unpacked and b != 0) or (unpacked and a > b):
                    continue
                sub = types[t.attrib['sub_dtype_id']]
            try:
                stride = width(sub)
                w = stride if unpacked else width(t)
                fs = fields(sub)
            except ValueError:
                continue
            key = 'TOP.'+cell.attrib['hier']+'.'+var.attrib['name']
            max_width = max(max_width, w)
            entries = ','.join('{"%s",{%d,%d}}'%x for x in fs)
            out.append('{"%s",{%d,%d,%d,%d,%s,{%s}}},' % (key,w,stride,low,high,str(unpacked).lower(),entries))
    out += ['};', 'inline const std::map<std::string,uint64_t> enum_values = {']
    seen = {}
    for t in types.values():
        for e in t.findall('enumitem'):
            c=e.find('const')
            if c is not None:
                try:
                    v=number(c.attrib['name'])
                    seen[e.attrib['name']]=v
                except (ValueError,KeyError):
                    pass
    out += ['{"%s",%dULL},'%(k,v) for k,v in sorted(seen.items())]
    out += ['};', 'inline const std::map<std::string,uint64_t> constants = {']
    for mod in (root.find("netlist/module[@name='tb_bare']"),root.find("netlist/package[@name='len5_config_pkg']")):
        for v in mod.findall('var'):
            c=v.find('const')
            if c is not None and (v.get('param') or v.get('localparam')):
                try:
                    out.append('{"%s.%s",%dULL},'%(mod.attrib['name'],v.attrib['name'],number(c.attrib['name'])))
                except (ValueError,KeyError):
                    pass
    out += ['};','}']
    Path(target).write_text('\n'.join(out)+'\n')
    return (max_width + 31)//32 + 1

if __name__ == '__main__':
    generate(*sys.argv[1:])
